### ISSUE TITLE
Which version to use with ESP 1.0.1 ?

### ISSUE THREAD

**Issue by HighTML** [ropg/M5ez#39]
Hi @ropg , the latest ESP32 1.0.2 has a bug (see https://github.com/espressif/arduino-esp32/issues/2786) so I need to downgrade to ESP 1.0.1. 

Now M5ez 2.1.0 "M5ez-demo" does not compile with ESP 1.0.1, and M5ez version 2.0.1 also does not compile with ESP 1.0.1. 

How can I get a version of M5ez running with ESP 1.0.1? 

Background: I need PubSubClient and it only compiles with ESP 1.0.1.

**ESP 1.0.1 with M5ez 2.1.0 or 2.0.1 or 2.0.0:**
`Arduino: 1.8.9 (Mac OS X), Board: "M5Stack-Core-ESP32, QIO, 80MHz, Default, 921600, None"`

`Build options changed, rebuilding all` 
`/Users/marcel/Development/Arduino/libraries/M5Stack/src/utility/Power.cpp: In member function 'void POWER::powerOFF()': /Users/marcel/Development/Arduino/libraries/M5Stack/src/utility/Power.cpp:361:28: error: 'gpio_deep_sleep_hold_dis' was not declared in this scope
   gpio_deep_sleep_hold_dis();
`
                     
`Multiple libraries were found for "WiFi.h"`
` Used: /Users/marcel/Library/Arduino15/packages/esp32/hardware/esp32/1.0.1/libraries/WiFi`
` Not used: /Applications/Arduino.app/Contents/Java/libraries/WiFi`
`Multiple libraries were found for "SD.h"`
` Used: /Users/marcel/Library/Arduino15/packages/esp32/hardware/esp32/1.0.1/libraries/SD`
` Not used: /Applications/Arduino.app/Contents/Java/libraries/SD`
`exit status 1`
`Error compiling for board M5Stack-Core-ESP32.`

**Comment by HighTML** [comment]
After a lot of trial and error... Found the answer myself. I need to downgrade ESP tot 1.0.1, M5ez to 2.0.1 **AND ** M5Stack to 0.2.6
